steps:
#  - name: gcr.io/$PROJECT_ID/docker-compose
#    env:
#      - 'K6_CLOUD_TOKEN=${_K6_CLOUD_TOKEN}'
#    args: ['run',
#           'k6',
#           'run',
#           '--no-connection-reuse',
#           '--insecure-skip-tls-verify',
#           '--no-teardown',
#           '--no-thresholds',
#           '--no-setup',
#           '--no-usage-report',
#           '--quiet',
#           '--out',
#           'cloud',
#           '/scripts/script.js']

  # Deploy container image to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: ['run', 'deploy',
        '$_SERVICE_NAME',
        '--image','gcr.io/$PROJECT_ID/$_SERVICE_NAME',
        '--region','$_REGION']
    timeout: 10s
# store artifact
images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'

# arguments
substitutions:
  _SERVICE_NAME:  'mock-server'
  _REGION:  'asia-northeast2'