steps:
  # build docker image(k6)
  - name: gcr.io/cloud-builders/docker
    args: [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/k6',
        '--cache-from', 'gcr.io/$PROJECT_ID/k6',
        '.'
    ]
    dir: 'k6'
    waitFor: ["-"]

  # build docker image(nginx)
  - name: gcr.io/cloud-builders/docker
    args: [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/${_MOCK_SERVER}',
        '--cache-from', 'gcr.io/$PROJECT_ID/${_MOCK_SERVER}',
        '.'
    ]
    dir: 'nginx'
    id: 'build-nginx'
    waitFor: ["-"]

  # build docker image(app)
  - name: gcr.io/cloud-builders/mvn
    args: [
        'compile', 'jib:build','-Dimage=eu.gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
    ]
    dir: 'core'
    id: 'build-app'
    waitFor: ["-"]

  # update nginx instances
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        gcloud compute instances update-container ${_MOCK_SERVER}-vm-1 \
        --zone=us-west1-b \
        --container-image=gcr.io/$PROJECT_ID/${_MOCK_SERVER}
    waitFor: ['build-nginx']

  # update nginx instances
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        gcloud compute instances update-container ${_MOCK_SERVER}-vm-2 \
        --zone=us-west1-b \
        --container-image=gcr.io/$PROJECT_ID/${_MOCK_SERVER}
    waitFor: ['build-nginx']

  # update app instances
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        gcloud compute instances update-container ${_SERVICE_NAME}-vm \
        --zone=us-west1-b \
        --container-image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}
    waitFor: ['build-app']

# store artifact
images:
  - 'gcr.io/$PROJECT_ID/${_MOCK_SERVER}'
  - 'gcr.io/$PROJECT_ID/k6'

# arguments
substitutions:
  _SERVICE_NAME: 'tiny-proxy'
  _NETWORK_TAG: 'load-test'
  _MOCK_SERVER: 'mock-http'
