steps:
  - name: gcr.io/$PROJECT_ID/docker-compose
    args:
      - run
      - k6
      - --no-connection-reuse
      - --insecure-skip-tls-verify
      - --no-teardown
      - --no-thresholds
      - --no-setup
      - --no-usage-report
      - --quiet
      - /scripts/script.js
