steps:
#  - name: gcr.io/$PROJECT_ID/docker-compose
#    env:
#      - 'K6_CLOUD_TOKEN=${_K6_CLOUD_TOKEN}'
#    args: ['run',
#           'k6',
#           'run',
#           '--no-connection-reuse',
#           '--insecure-skip-tls-verify',
#           '--no-teardown',
#           '--no-thresholds',
#           '--no-setup',
#           '--no-usage-report',
#           '--quiet',
#           '--out',
#           'cloud',
#           '/scripts/script.js']

#  - name: gcr.io/$PROJECT_ID/gcloud

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        gcloud run deploy ${_SERVICE_NAME}-$BUILD_ID \
          --image gcr.io/$PROJECT_ID/mock-server \
          --region ${_REGION} \
          --ingress=internal \
          --timeout=10s
# arguments
substitutions:
  _SERVICE_NAME: 'tiny-proxy'
  _REGION: 'asia-northeast2'