steps:
  - name: gcr.io/$PROJECT_ID/docker-compose
    env:
      - 'K6_CLOUD_TOKEN=${_K6_TOKEN}'
    args: ['run',
           'k6',
           'run',
           '--no-connection-reuse',
           '--insecure-skip-tls-verify',
           '--no-teardown',
           '--no-thresholds',
           '--no-setup',
           '--no-usage-report',
           '--quiet',
           '--out',
           'cloud',
           '/scripts/script.js']
