steps:
  # set firewall-rules
#  - name: gcr.io/$PROJECT_ID/gcloud
#    entrypoint: /bin/bash
#    args:
#      - '-c'
#      - |
#        gcloud compute firewall-rules create http-inbound \
#        --allow tcp:80 \
#        --target-tags ${_NETWORK_TAG}

  # build docker image(k6)
  - name: gcr.io/cloud-builders/docker
    args: [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/k6',
        '--cache-from', 'gcr.io/$PROJECT_ID/k6',
        '.'
    ]
    dir: 'k6'
    waitFor: ["-"]

  # build docker image(nginx)
  - name: gcr.io/cloud-builders/docker
    args: [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/${_MOCK_SERVER}',
        '--cache-from', 'gcr.io/$PROJECT_ID/${_MOCK_SERVER}',
        '.'
    ]
    dir: 'nginx'
    id: 'build-nginx'
    waitFor: ["-"]

  # build docker image(app)
  - name: gcr.io/cloud-builders/mvn
    args: [
        'compile', 'jib:build','-Dimage=eu.gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
    ]
    dir: 'core'
    id: 'build-app'
    waitFor: ["-"]

  # deploy and run app instances
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        gcloud compute instances create-with-container ${_SERVICE_NAME}-vm --quiet \
              --zone=us-west1-b \
              --machine-type=e2-micro \
              --image-project=cos-cloud \
              --image-family=cos-97-lts \
              --container-image=gcr.io/$PROJECT_ID/${_SERVICE_NAME} \
              --container-restart-policy=never
              --tags ${_NETWORK_TAG}
    waitFor: ['build-app']

  # deploy and run nginx instances
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        gcloud compute instances create-with-container ${_MOCK_SERVER}-vm-1 ${_MOCK_SERVER}-vm-2 --quiet \
              --zone=us-west1-b \
              --machine-type=e2-micro \
              --image-project=cos-cloud \
              --image-family=cos-97-lts \
              --container-image=gcr.io/$PROJECT_ID/${_MOCK_SERVER} \
              --container-restart-policy=never
              --tags ${_NETWORK_TAG}
    waitFor: ['build-nginx']

# store artifact
images:
  - 'gcr.io/$PROJECT_ID/${_MOCK_SERVER}'
  - 'gcr.io/$PROJECT_ID/k6'
# arguments
substitutions:
  _SERVICE_NAME: 'tiny-proxy'
  _NETWORK_TAG: 'load-test'
  _MOCK_SERVER: 'mock-http'
