version: '3.4'
services:
  k6:
    image: grafana/k6:latest
    container_name: k6
    privileged: true
    ports:
      - "6565:6565"
    volumes:
      - ./scripts:/scripts
    environment:
      - K6_CLOUD_TOKEN=${K6_CLOUD_TOKEN}
    env_file:
      - .env